import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarPC from "@/components/navbar/NavbarPC";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "@/context/authContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ToastContainer position="top-center" />
          <NavbarPC />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
